// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9gE7XPQtA4hJrDaH24TFQjNQLnY8AQC8',
    appId: '1:682561257918:web:235d4a99ae7d3be37b39ef',
    messagingSenderId: '682561257918',
    projectId: 'hospitalsanalejo',
    authDomain: 'hospitalsanalejo.firebaseapp.com',
    storageBucket: 'hospitalsanalejo.appspot.com',
    measurementId: 'G-63RZ78D4V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8IfXRspmSWshkBgiwSModCuP2h2dQP0',
    appId: '1:682561257918:android:2bf777ef746e4dc27b39ef',
    messagingSenderId: '682561257918',
    projectId: 'hospitalsanalejo',
    storageBucket: 'hospitalsanalejo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDWoeUbZHgc1xuP1LH3eKIX-1iKM1wSZw',
    appId: '1:682561257918:ios:c73b2c5cbac6fe827b39ef',
    messagingSenderId: '682561257918',
    projectId: 'hospitalsanalejo',
    storageBucket: 'hospitalsanalejo.appspot.com',
    iosBundleId: 'com.example.hospitalsanalejo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDWoeUbZHgc1xuP1LH3eKIX-1iKM1wSZw',
    appId: '1:682561257918:ios:c73b2c5cbac6fe827b39ef',
    messagingSenderId: '682561257918',
    projectId: 'hospitalsanalejo',
    storageBucket: 'hospitalsanalejo.appspot.com',
    iosBundleId: 'com.example.hospitalsanalejo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9gE7XPQtA4hJrDaH24TFQjNQLnY8AQC8',
    appId: '1:682561257918:web:ac362e60a4ffcb007b39ef',
    messagingSenderId: '682561257918',
    projectId: 'hospitalsanalejo',
    authDomain: 'hospitalsanalejo.firebaseapp.com',
    storageBucket: 'hospitalsanalejo.appspot.com',
    measurementId: 'G-E1VC6FPD4J',
  );
}
